### PR TITLE
changing BREC link from hive to inside.barnardos

### LINKED ISSUE #433: Fix BREC Guidance link on Researcher step
## Description

The link to BREC Guidance on the Researcher step is broken. We need to update the link to go to https://inside.barnardos.org.uk/resources-and-guidance/research-and-information/barnardos-research-ethics-committee-brec

## Step to reproduce

1. Go to https://consent-form.barnardos.digital/
2. Click start
3. Create a new consent form with any name
4. Click the BREC Guidance link
5. Notice how the page errors

## Expected outcome

The page should show information about BREC.

### PR DESCRIPTION
**Pull request by rinkashimikito**
Fixes #433 

PR Review link:
https://consent-form-builder-st-pr-434.herokuapp.com

### CODE REVIEW

**Comment by olliewright** [comment]
@rinkashimikito the BREC link works fine and i succesfully generated a consent form. 

The consent form PDF generation does not work now though.

The expected PDF should be formatted to display all the information for end users to complete and sign manually.

If you look at the attached PDF the first page is blank and the 2nd page has information missing from the bottom of the form. 

Here is the form I generated with all the information that should be in the PDF.

https://consent-form-builder-st-pr-434.herokuapp.com/research-sessions/plymouth-pics-(copy)/preview

[Preview & print – my test session.pdf](https://github.com/barnardos/consent-form-builder/files/3280872/Preview.print.my.test.session.pdf)

**Comment by rinkashimikito** [comment]
@olliewright great!

The saving to pdf issue exists on production as well so this is not something related to this issue. I'll merge this one and create a new issue addressing the save to pdf if that's ok with you?

**Comment by olliewright** [comment]
great perfect thanks M!

**Comment by rinkashimikito** [comment]
@olliewright Cool, all I need to ask you now is to approve this PR so I can merge it.

https://help.github.com/en/articles/approving-a-pull-request-with-required-reviews

**Pull request merged**
